from qiskit import QuantumCircuit, execute, Aer, QuantumRegister, ClassicalRegister
num_qubits = 6

def rand_cliff_06(mqc):
    q = QuantumRegister(num_qubits)
    c = ClassicalRegister(num_qubits)
    qc = QuantumCircuit(q, c)

    for i in range(num_qubits):
        qc.h(i)

    qc = mqc.compose(qc)

    qc.x(4)
    qc.z(4)
    qc.x(3)
    qc.x(2)
    qc.z(0)
    qc.h(5)
    qc.sdg(5)
    qc.h(5)
    qc.h(5)
    qc.h(4)
    qc.h(3)
    qc.cx(3,5)
    qc.h(3)
    qc.cx(4,3)
    qc.swap(4,3)
    qc.h(4)
    qc.h(2)
    qc.sdg(2)
    qc.cx(2,5)
    qc.cx(2,4)
    qc.cx(2,3)
    qc.h(2)
    qc.cx(5,2)
    qc.sdg(2)
    qc.cx(5,2)
    qc.cx(4,2)
    qc.cx(2,4)
    qc.swap(3,2)
    qc.h(1)
    qc.cx(1,5)
    qc.cx(1,2)
    qc.h(1)
    qc.cx(3,1)
    qc.sdg(1)
    qc.cx(5,1)
    qc.cx(4,1)
    qc.cx(3,1)
    qc.cx(1,4)
    qc.cx(1,2)
    qc.h(0)
    qc.sdg(0)
    qc.cx(0,5)
    qc.cx(0,3)
    qc.h(0)
    qc.cx(5,0)
    qc.sdg(0)
    qc.cx(5,0)
    qc.cx(4,0)
    qc.cx(3,0)
    qc.cx(1,0)
    qc.sdg(0)
    qc.cx(0,5)
    qc.swap(4,0)

    for i in range(num_qubits):
        qc.measure(i, i)

    backend = Aer.get_backend("aer_simulator")
    job = execute(qc, backend, shots = 100000).result().get_counts(qc)
    return job